### PR TITLE
Completed landing page(hero page)

### PR DESCRIPTION
**Pull request by AkshatDobriyal**

### CODE REVIEW

**Comment by AkshatDobriyal** [comment]
image
image
image

**Comment by prathmeshkhandelwal1** [comment]
@AkshatDobriyal dont put this much of commit.

**Comment by AkshatDobriyal** [comment]
> @AkshatDobriyal dont put this much of commit.
Ok
But several commits were made just to resolve conflicts.

**Comment by AkshatDobriyal** [comment]
> @prathmeshkhandelwal1 delete the Components directory with uppercase C and just keep the components directory with lowercase c.

@prathmeshkhandelwal1 I have transferred the login component to components directory, so please delete the Components directory.

**Comment by prathmeshkhandelwal1** [comment]
> > @prathmeshkhandelwal1 delete the Components directory with uppercase C and just keep the components directory with lowercase c.
> 
> @prathmeshkhandelwal1 I have transferred the login component to components directory, so please delete the Components directory.

Okkk

**Pull request merged**
