### PR TITLE
Feat : Completed Login Page  

### PR DESCRIPTION
**Pull request by raghusodani**
regarding issue#6
styling of buttons remaining.

### CODE REVIEW

**Comment by prathmeshkhandelwal1** [comment]
@raghusodani completed?

**Comment by raghusodani** [comment]
@prathmeshkhandelwal1 everything is done!! Don't mind too many commits.

**Comment by prathmeshkhandelwal1** [comment]
Add SS of pages @raghusodani

**Comment by raghusodani** [comment]
Screenshot (281)

**Review by prathmeshkhandelwal1 — APPROVED** [review]
LGTM

**Pull request merged**
