### PR TITLE
Feat/Completed Navbar according to design

### PR DESCRIPTION
**Pull request by AkshatDobriyal**
Regarding issue#4

### CODE REVIEW

**Comment by prathmeshkhandelwal1** [comment]
@AkshatDobriyal is this done?

**Comment by AkshatDobriyal** [comment]
> @AkshatDobriyal is this done?

Yes

**Comment by prathmeshkhandelwal1** [comment]
Can you add proper Screenshot of pages.

**Comment by AkshatDobriyal** [comment]
> Can you add proper Screenshot of pages.

Sure
image

**Comment by prathmeshkhandelwal1** [comment]
@AkshatDobriyal Dont use this much commit for minor feature. otherwise LGTM.

**Review by prathmeshkhandelwal1 — APPROVED** [review]

**Pull request merged**
